INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Administración base de datos Oracle', 'Construcción y administración de una base de datos basada en los sitemas de Oracle.', 'https://www.interviewbit.com/blog/wp-content/uploads/2021/08/cover-800x390.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Aplicación de Gestión de Tareas', 'Desarrollo de una aplicación para la gestión de tareas personal y en equipo. Incluye funciones de asignación de tareas, seguimiento de tiempo y notificaciones.', 'https://assets.goodfirms.co/images/1557988238-app-image.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Sistema de Reservas para Hotel', 'Desarrollo de un sistema de reservas en línea para un hotel. Permite a los clientes reservar habitaciones, ver disponibilidad y gestionar sus reservas.', 'https://www.technoheaven.net/Theme/img/Hotel-Booking-Software.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Plataforma de Aprendizaje en Línea', 'Creación de una plataforma de aprendizaje en línea con cursos interactivos, evaluaciones y seguimiento del progreso del estudiante.', 'https://cdn.elearningindustry.com/wp-content/uploads/2022/01/shutterstock_1060195475.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Aplicación de Red Social', 'Desarrollo de una red social para conectar personas con intereses comunes. Incluye funciones de publicación de contenido, seguimiento de usuarios y mensajería.', 'https://as1.ftcdn.net/v2/jpg/04/30/58/30/1000_F_430583045_8pzUfNcSDkkNakHGMvzH1TYbPEPnE7KC.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Sistema de Gestión de Proyectos', 'Desarrollo de una herramienta para la gestión eficiente de proyectos. Permite crear, asignar y hacer seguimiento de tareas y proyectos.', 'https://miro.medium.com/v2/resize:fit:624/1*Ghby7MNd-ERYy8yimuZP6w.png');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Plataforma de Streaming de Video', 'Construcción de una plataforma de streaming de video para transmitir contenido en tiempo real. Incluye funciones de reproducción, lista de reproducción y búsqueda.', 'https://thecrimsonwhite.com/wp-content/uploads/2021/06/streaming-900x472.png');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Aplicación de Control de Inventario', 'Desarrollo de una aplicación para gestionar el inventario de una empresa. Permite realizar seguimiento de productos, control de stock y generar informes.', 'https://assets-global.website-files.com/608710000c1ca91d9e5c79bb/649f4397d432f93094c35e47_control%20inventario%20sistema.webp');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Herramienta de Análisis de Datos', 'Creación de una herramienta para el análisis de datos en tiempo real. Permite visualizar y procesar grandes volúmenes de datos de forma eficiente.', 'https://monkeylearn.com/static/1e4342e7c9c1aca92ab69cdb9bc7a1fe/Top-Data-Analysis-Tools-Social.png');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Sistema de Gestión de Contenidos', 'Desarrollo de un sistema para la gestión de contenidos web. Permite crear, editar y publicar contenido de manera colaborativa.', 'https://blog.hubspot.com/hs-fs/hubfs/Image%20Pack-CMS%20-72-png.webp?width=650&height=394&name=Image%20Pack-CMS%20-72-png.webp');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Plataforma de Resolución de Problemas', 'Construcción de una plataforma para resolver problemas técnicos y de programación. Incluye un sistema de votación para las soluciones más útiles.', 'https://cdn-developer-wp.arc.dev/wp-content/uploads/2021/12/problem-solving-skills-for-software-developers-1128x635.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Aplicación de Mensajería Instantánea', 'Desarrollo de una aplicación de mensajería instantánea para la comunicación entre usuarios. Incluye funciones de chat grupal, llamadas de voz y videollamadas.', 'https://www.muycomputer.com/wp-content/uploads/2022/07/Aplicaciones_de_Mensajeria_3.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Sistema de Gestión de Recursos Humanos', 'Creación de un sistema para la gestión de recursos humanos en una empresa. Permite gestionar empleados, nóminas y evaluaciones de desempeño.', 'https://peoplespheres.com/wp-content/uploads/2023/02/ERM%20.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Plataforma de Seguimiento de Fitness', 'Desarrollo de una plataforma para el seguimiento de actividades físicas y salud. Permite registrar entrenamientos, establecer objetivos y hacer seguimiento de progreso.', 'https://www.peerbits.com/static/6142f24615d2c569d410992301613e62/87e8a/fitness-tracking-app-mains.jpg');
INSERT INTO proyectos(nombre, descripcion, imagen) VALUES ('Aplicación de Realidad Aumentada', 'Construcción de una aplicación de realidad aumentada para dispositivos móviles. Permite superponer objetos virtuales en el mundo real.', 'https://miro.medium.com/v2/resize:fit:701/1*H1DDZz7ofDqZm65wlG0pIg.png');

INSERT INTO usuarios(nick, contrasena) VALUES ('Emi', 'Abcd1234');
INSERT INTO usuarios(nick, contrasena) VALUES ('Joseca', 'Abcd1234');